### PR TITLE
Correcting the endpoint URI link format to match the latest changes i…

### PR DESCRIPTION
**Pull request by RohitMungi-MSFT**
…n Azure

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?
Corrects the placeholder for endpoint 

```
[ x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Run the python script with the suggested endpoint changes and check if the KB is created for your Azure QnA resource in Azure portal
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Check if the KB is created for your QnA resource

### CODE REVIEW

**Comment by diberry** [comment]
@RohitMungi-MSFT Why are you going back to using a region name? Did someone from PG ask for this? It is against guidance from @ChrisHMSFT and central platform team. #hold-off

**Comment by RohitMungi-MSFT** [comment]
@diberry Thanks for the clarification. I was not aware of the guidance from the team. In this case we can use the resource name `<your-resource-name>.cognitiveservices.azure.com` instead of `<your-resource-name>.api.cognitive.microsoft.com` as the latter does not work.

**Comment by diberry** [comment]
@RohitMungi-MSFT The domain is incorrect. That changes isn't in the PR. Were you intending to make that change?

**Comment by RohitMungi-MSFT** [comment]
@diberry Sorry for the typo in my earlier comment. I was actually not aware about the guidance from the PG. I will go ahead and raise a new PR to ensure the host is set to the following.
`host = '<your-resource-name>.cognitiveservices.azure.com'
`

**Pull request closed without merging**
